# Generated by Django 4.1.10 on 2023-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
