# Generated by Django 4.1.10 on 2023-08-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='court_name',
            new_name='court',
        ),
    ]
